### ISSUE TITLE
Simulation 'fails' with EVENT_RUN_STOP

### ISSUE THREAD

**Issue by TACD** [SpineML/SpineCreator#99] opened 2016-02-04 16:38 UTC
When running either the 'intrinsic' or 'TRN' models in Models/Rate-coded BG (see commit [weibull 7b0acb5]) the SpineCreator output ends with:

**Comment by TACD** [comment] 2016-02-04 16:39
W10   0.336185       FINISHED
W10   0.336227       FINISHED
W10   0.336246       FINISHED
W13   0.338335       FINISHED
W16   0.339441       FINISHED
E_USER: Could not open state variable file: 
    whilst firing EVENT_RUN_STOP on GPe_to_STN_Synapse_0_weight_update

E_USER: Could not open state variable file: 
    whilst firing EVENT_RUN_STOP on GPi_SNr_to_VL_thalamus_Synapse_0_weight_update

E_USER: Could not open state variable file: 
    whilst firing EVENT_RUN_STOP on VL_thalamus_to_Motor_Cortex_Synapse_0_weight_update

...and several more such errors. However the simulation actually runs fine and all logfiles are generated as normal, so I'm not really sure what the 'error' is referring to.

**Comment by ajc158** [comment] 2016-02-04 18:17
I just fixed this today - I'll move the fix from my branch to the master
branch. The culprit is a single missing $!

**Comment by ajc158** [comment] 2016-02-04 18:20
The problem is that State Variables for WeightUpdates are not saved out at
the end of the simulation. This is a problem for learning simulations as
you can't resume from a trained system. Do these WeightUpdates change their
weights internally? If not you shouldn't need a State Variable (and it will
slow simulation)

**Comment by ajc158** [comment] 2016-02-04 19:48
Fixed in SpineML_2_BRAHMS 91bbed1

**Closed by ajc158** 2016-02-04 19:48 UTC
